// <auto-generated />
using CustomerManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CustomerManagement.Migrations
{
    [DbContext(typeof(StoreDataContext))]
    [Migration("20201015221013_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerManagement.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("EnderecoBairro")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("EnderecoCep")
                        .HasColumnType("varchar(9)")
                        .HasMaxLength(9);

                    b.Property<string>("EnderecoCidade")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("EnderecoEstado")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<string>("EnderecoLogradouro")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("EnderecoNro")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("NomeContato")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("varchar(120)")
                        .HasMaxLength(120);

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
